"""Create tables

Revision ID: 1dd629dce41f
Revises: c83b49a20116
Create Date: 2025-10-01 09:58:53.509020

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1dd629dce41f'
down_revision: str | Sequence[str] | None = 'c83b49a20116'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine',
    sa.Column('routine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('routine')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routine')
    # ### end Alembic commands ###
