"""Create tables

Revision ID: 23b66e780216
Revises: 1dd629dce41f
Create Date: 2025-10-01 10:10:47.268089

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '23b66e780216'
down_revision: str | Sequence[str] | None = '1dd629dce41f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine', sa.Column('energy_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routine', 'energy_level')
    # ### end Alembic commands ###
