"""Create tables

Revision ID: a160422adaf5
Revises: 23b66e780216
Create Date: 2025-10-01 10:23:08.295700

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a160422adaf5'
down_revision: str | Sequence[str] | None = '23b66e780216'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routine', 'id')
    # ### end Alembic commands ###
