"""Create tables

Revision ID: c0d0e2749f90
Revises: 3fd5b25819c9
Create Date: 2025-10-01 10:33:14.823586

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c0d0e2749f90'
down_revision: str | Sequence[str] | None = '3fd5b25819c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routine')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine',
    sa.Column('routine', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('energy_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('routine', name=op.f('routine_pkey'))
    )
    # ### end Alembic commands ###
