"""Create tables

Revision ID: c83b49a20116
Revises: b3b5eac10a74
Create Date: 2025-09-30 12:27:32.360373

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c83b49a20116'
down_revision: str | Sequence[str] | None = 'b3b5eac10a74'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_optional')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_optional', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
